import { SkillMajor } from "./skill";
import { Attribute } from "./character";

export enum SkillCheck {
    REFLEX = SkillMajor.REFLEX,
    OVERRUN = SkillMajor.OVERRUN,
    BALANCE = SkillMajor.BALANCE,
    JUMP = SkillMajor.JUMP,
    CLIMB = SkillMajor.CLIMB,
    ESCAPE = SkillMajor.ESCAPE,
    SWIM = SkillMajor.SWIM,
    GRAPPLE = SkillMajor.GRAPPLE,
    BUMP = SkillMajor.BUMP,
    WINGCLIP = SkillMajor.WINGCLIP,
    UNLOCK = SkillMajor.UNLOCK,
    STEAL = SkillMajor.STEAL,
    HIDE_ITEM = SkillMajor.HIDE_ITEM,
    TIEDUP = SkillMajor.TIEDUP,
    HIDE = SkillMajor.HIDE,
    STEALTH = SkillMajor.STEALTH,
    WILDERNESS_SURVIVAL = SkillMajor.WILDERNESS_SURVIVAL,
    FORTITUDE = SkillMajor.FORTITUDE,
    TRACE = SkillMajor.TRACE,
    FILE_DECRYPTION = SkillMajor.FILE_DECRYPTION,
    MONSTER = SkillMajor.MONSTER,
    HACKER = SkillMajor.HACKER,
    FIREWALL = SkillMajor.FIREWALL,
    COMPUTER_GAME = SkillMajor.COMPUTER_GAME,
    COMPUTER_USE = SkillMajor.COMPUTER_USE,
    SEARCH = SkillMajor.SEARCH,
    LISTEN = SkillMajor.LISTEN,
    RECON = SkillMajor.RECON,
    READ_LIP = SkillMajor.READ_LIP,
    FIRST_AID = SkillMajor.FIRST_AID,
    NURSE = SkillMajor.NURSE,
    DIAGNOSIS = SkillMajor.DIAGNOSIS,
    CURE = SkillMajor.CURE,
    SPELLCRAFT = SkillMajor.SPELLCRAFT,
    BEASTMASTERY = SkillMajor.BEASTMASTERY,
    BEAST_LANGUAGE = SkillMajor.BEAST_LANGUAGE,
    FIRM_STAND = SkillMajor.FIRM_STAND,
    SENSE_MOTIVE = SkillMajor.SENSE_MOTIVE,
    SING = SkillMajor.SING,
    PLAY = SkillMajor.PLAY,
    DANCE = SkillMajor.DANCE,
    PHYSICALLY_ACT = SkillMajor.PHYSICALLY_ACT,
    SPEECH = SkillMajor.SPEECH,
    INTIMIDATE = SkillMajor.INTIMIDATE,
    ROAR = SkillMajor.ROAR,
    NEGOTIATE = SkillMajor.NEGOTIATE,
    CONVINCE = SkillMajor.CONVINCE,
    COLLECTING_INFO = SkillMajor.COLLECTING_INFO,
    FEINT = SkillMajor.FEINT,
    BLUFFING = SkillMajor.BLUFFING,
    DISGUISE = SkillMajor.DISGUISE,
    CAMOUFLAGE = SkillMajor.CAMOUFLAGE,
  };

export const SkillCheckMap = {
  [SkillCheck.REFLEX]: "反射检定",
  [SkillCheck.OVERRUN]: "闯越",
  [SkillCheck.BALANCE]: "平衡感",
  [SkillCheck.JUMP]: "跳跃",
  [SkillCheck.CLIMB]: "攀爬",
  [SkillCheck.ESCAPE]: "逃脱",
  [SkillCheck.SWIM]: "游泳",
  [SkillCheck.GRAPPLE]: "擒抱",
  [SkillCheck.BUMP]: "冲撞",
  [SkillCheck.WINGCLIP]: "摔绊",
  [SkillCheck.UNLOCK]: "开锁",
  [SkillCheck.STEAL]: "盗窃",
  [SkillCheck.HIDE_ITEM]: "隐藏物品",
  [SkillCheck.TIEDUP]: "捆绑",
  [SkillCheck.HIDE]: "躲藏",
  [SkillCheck.STEALTH]: "潜行",
  [SkillCheck.WILDERNESS_SURVIVAL]: "自然环境生存",
  [SkillCheck.FORTITUDE]: "强韧检定",
  [SkillCheck.TRACE]: "追踪",
  [SkillCheck.FILE_DECRYPTION]: "文件解读",
  [SkillCheck.MONSTER]: "怪物知识",
  [SkillCheck.HACKER]: "黑客入侵",
  [SkillCheck.FIREWALL]: "防火墙",
  [SkillCheck.COMPUTER_GAME]: "打游戏",
  [SkillCheck.COMPUTER_USE]: "编程",
  [SkillCheck.SEARCH]: "搜索",
  [SkillCheck.LISTEN]: "聆听",
  [SkillCheck.RECON]: "侦查",
  [SkillCheck.READ_LIP]: "读唇",
  [SkillCheck.FIRST_AID]: "急救",
  [SkillCheck.NURSE]: "长线治疗",
  [SkillCheck.DIAGNOSIS]: "诊断",
  [SkillCheck.CURE]: "治疗",
  [SkillCheck.SPELLCRAFT]: "法术辨识",
  [SkillCheck.BEASTMASTERY]: "训练动物",
  [SkillCheck.BEAST_LANGUAGE]: "改善动物态度",
  [SkillCheck.FIRM_STAND]: "检定立场",
  [SkillCheck.SENSE_MOTIVE]: "察言观色",
  [SkillCheck.SING]: "唱歌",
  [SkillCheck.PLAY]: "演奏",
  [SkillCheck.DANCE]: "舞蹈",
  [SkillCheck.PHYSICALLY_ACT]: "肢体表演",
  [SkillCheck.SPEECH]: "演讲",
  [SkillCheck.INTIMIDATE]: "威吓",
  [SkillCheck.ROAR]: "咆哮",
  [SkillCheck.NEGOTIATE]: "交涉",
  [SkillCheck.CONVINCE]: "说服",
  [SkillCheck.COLLECTING_INFO]: "收集情报",
  [SkillCheck.FEINT]: "虚招",
  [SkillCheck.BLUFFING]: "唬骗",
  [SkillCheck.DISGUISE]: "易容",
  [SkillCheck.CAMOUFLAGE]: "伪装",
};

export const SkillCheckAttribute: {
    [key in SkillCheck]: Attribute[];
} = {
  [SkillCheck.REFLEX]: [Attribute.DEXTERITY],
  [SkillCheck.OVERRUN]: [Attribute.DEXTERITY, Attribute.STRENGTH],
  [SkillCheck.BALANCE]: [Attribute.DEXTERITY],
  [SkillCheck.JUMP]: [Attribute.STRENGTH],
  [SkillCheck.CLIMB]: [Attribute.STRENGTH],
  [SkillCheck.ESCAPE]: [Attribute.DEXTERITY],
  [SkillCheck.SWIM]: [Attribute.STRENGTH],
  [SkillCheck.GRAPPLE]: [Attribute.STRENGTH],
  [SkillCheck.BUMP]: [Attribute.STRENGTH],
  [SkillCheck.WINGCLIP]: [Attribute.STRENGTH],
  [SkillCheck.UNLOCK]: [Attribute.INTELLIGENCE],
  [SkillCheck.STEAL]: [Attribute.DEXTERITY],
  [SkillCheck.HIDE_ITEM]: [Attribute.INTELLIGENCE],
  [SkillCheck.TIEDUP]: [Attribute.INTELLIGENCE],
  [SkillCheck.HIDE]: [Attribute.DEXTERITY],
  [SkillCheck.STEALTH]: [Attribute.DEXTERITY],
  [SkillCheck.WILDERNESS_SURVIVAL]: [Attribute.WISDOM],
  [SkillCheck.FORTITUDE]: [Attribute.CONSTITUTION],
  [SkillCheck.TRACE]: [Attribute.WISDOM],
  [SkillCheck.FILE_DECRYPTION]: [Attribute.INTELLIGENCE],
  [SkillCheck.MONSTER]: [Attribute.INTELLIGENCE],
  [SkillCheck.HACKER]: [Attribute.INTELLIGENCE],
  [SkillCheck.FIREWALL]: [Attribute.INTELLIGENCE],
  [SkillCheck.COMPUTER_GAME]: [Attribute.INTELLIGENCE],
  [SkillCheck.COMPUTER_USE]: [Attribute.INTELLIGENCE],
  [SkillCheck.SEARCH]: [Attribute.INTELLIGENCE],
  [SkillCheck.LISTEN]: [Attribute.WISDOM],
  [SkillCheck.RECON]: [Attribute.WISDOM],
  [SkillCheck.READ_LIP]: [Attribute.WISDOM],
  [SkillCheck.FIRST_AID]: [Attribute.DEXTERITY],
  [SkillCheck.NURSE]: [Attribute.INTELLIGENCE],
  [SkillCheck.DIAGNOSIS]: [Attribute.INTELLIGENCE],
  [SkillCheck.CURE]: [Attribute.INTELLIGENCE],
  [SkillCheck.SPELLCRAFT]: [Attribute.INTELLIGENCE],
  [SkillCheck.BEASTMASTERY]: [Attribute.CONTROL],
  [SkillCheck.BEAST_LANGUAGE]: [Attribute.CONTROL],
  [SkillCheck.FIRM_STAND]: [Attribute.DETERMINATION, Attribute.COMPOSURE],
  [SkillCheck.SENSE_MOTIVE]: [Attribute.WISDOM],
  [SkillCheck.SING]: [Attribute.CHARISMA],
  [SkillCheck.PLAY]: [Attribute.CHARISMA],
  [SkillCheck.DANCE]: [Attribute.CHARISMA],
  [SkillCheck.PHYSICALLY_ACT]: [Attribute.CHARISMA],
  [SkillCheck.SPEECH]: [Attribute.CHARISMA],
  [SkillCheck.INTIMIDATE]: [Attribute.CONTROL],
  [SkillCheck.ROAR]: [Attribute.STRENGTH],
  [SkillCheck.NEGOTIATE]: [Attribute.CONTROL],
  [SkillCheck.CONVINCE]: [Attribute.CONTROL],
  [SkillCheck.COLLECTING_INFO]: [Attribute.CONTROL],
  [SkillCheck.FEINT]: [Attribute.INTELLIGENCE],
  [SkillCheck.BLUFFING]: [Attribute.CONTROL],
  [SkillCheck.DISGUISE]: [Attribute.INTELLIGENCE],
  [SkillCheck.CAMOUFLAGE]: [Attribute.INTELLIGENCE],
};
